version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ElevateU-Server
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "no"
      MYSQL_DATABASE: "ElevateU-DB"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel_network
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - laravel-app
    networks:
      - laravel_network
  frontend:
    image: your-frontend-image
    environment:
      - NEXT_PUBLIC_API_URL=http://laravel-app:8080/ # Use the service name 'laravel-app'
    # other configurations...

networks:
  laravel_network: {}

volumes:
  mysql_data: {}
